# Generated by Django 4.1.1 on 2022-09-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0005_remove_product_image_remove_product_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
