# Generated by Django 4.1.1 on 2022-09-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0009_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='right_image',
        ),
    ]
