# Generated by Django 4.1.1 on 2022-09-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0010_remove_product_right_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='modo_uso',
        ),
        migrations.AddField(
            model_name='product',
            name='ingredienti',
            field=models.TextField(blank=True, null=True),
        ),
    ]
