# Generated by Django 4.1.1 on 2022-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0011_rename_description_product_modo_uso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, null=True),
        ),
    ]
