# Generated by Django 4.1.1 on 2022-09-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodotti', '0012_product_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
